/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TornAccountRouteImport } from './routes/torn-account'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LevellingListRouteImport } from './routes/levelling-list'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const TornAccountRoute = TornAccountRouteImport.update({
  id: '/torn-account',
  path: '/torn-account',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LevellingListRoute = LevellingListRouteImport.update({
  id: '/levelling-list',
  path: '/levelling-list',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/levelling-list': typeof LevellingListRoute
  '/login': typeof LoginRoute
  '/torn-account': typeof TornAccountRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/levelling-list': typeof LevellingListRoute
  '/login': typeof LoginRoute
  '/torn-account': typeof TornAccountRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/levelling-list': typeof LevellingListRoute
  '/login': typeof LoginRoute
  '/torn-account': typeof TornAccountRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/levelling-list' | '/login' | '/torn-account'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/levelling-list' | '/login' | '/torn-account'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/levelling-list'
    | '/login'
    | '/torn-account'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LevellingListRoute: typeof LevellingListRoute
  LoginRoute: typeof LoginRoute
  TornAccountRoute: typeof TornAccountRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/torn-account': {
      id: '/torn-account'
      path: '/torn-account'
      fullPath: '/torn-account'
      preLoaderRoute: typeof TornAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levelling-list': {
      id: '/levelling-list'
      path: '/levelling-list'
      fullPath: '/levelling-list'
      preLoaderRoute: typeof LevellingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LevellingListRoute: LevellingListRoute,
  LoginRoute: LoginRoute,
  TornAccountRoute: TornAccountRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
